#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define SCREEN_X_SIZE 800
#define SCREEN_Y_SIZE 600

#define DEFAULT_SERVER_IP "127.0.0.1"
#define DEFAULT_SERVER_PORT 8080
#define DEFAULT_MAX_CLIENTS 3

#endif