#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define SCREEN_X_SIZE 800
#define SCREEN_Y_SIZE 600

#define OPT_TRUE 1
#define OPT_FALSE 0

#define DEFAULT_SERVER_IP "127.0.0.1"
#define DEFAULT_SERVER_PORT 8080
#define MAX_PLAYERS 4
#define MAX_CLIENTS (MAX_PLAYERS - 1)
#define DEFAULT_RENDERING_DELAY_MS 10
#define DEFAULT_LISTEN_TIMEOUT_US 1000 * 1

#endif